### ISSUE TITLE
Jenkins pipeline

### ISSUE THREAD

**Issue by ghost** [osixia/docker-light-baseimage#10]
I have used this image in Jenkins pipeline, it never starts and too many permission issues as below

*** CONTAINER_LOG_LEVEL = 3 (info)
*** Killing all processes...
Traceback (most recent call last):
  File "/container/tool/run", line 890, in <module>
    main(args)
  File "/container/tool/run", line 775, in main
    setup_run_directories(args)
  File "/container/tool/run", line 371, in setup_run_directories
    os.chown(RUN_ENVIRONMENT_FILE_EXPORT, uid, gid)
OSError: [Errno 1] Operation not permitted: '/container/run/environment.sh'

**Comment by BertrandGouny** [comment]
I’m going to close this issue since v2 is coming soon and the entire codebase has been fully rewritten in Go.
With the new architecture, this issue is no longer relevant.
Thank you for taking the time to report it, and sorry for the inconvenience.
